### ISSUE TITLE
開発ルールを作成する

### ISSUE THREAD

**Issue by KadoProG** [hack-CommTech/routify-app#1]
一旦ここ（README.mdに書くでもOK）で意見を出すようにしましょう

@TakuyaKubo7140 前回のチームの開発ルールをREADME.mdに書いてもらってプルリク出してもらっていいでしょうか？

**Comment by TakuyaKubo7140** [comment]
了解です。書き次第プルリク出します。

**Comment by TakuyaKubo7140** [comment]
あとプロジェクト作成したので、そこでタスク管理しましょう。
